services:
  db:
    image: postgres:17
    container_name: db
    environment:
      POSTGRES_DB: meu-deputado
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

  backend:
    build:
      context: ./api
    container_name: laravel-app
    command: >
      sh -c "
        php artisan migrate &&
        php artisan queue:work &
        php artisan sync:partidos &&
        php artisan sync:deputados &&
        php artisan serve --host=0.0.0.0 --port=8000
      "
    volumes:
      - ./api:/var/www
    working_dir: /var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_network

  frontend:
    build:
      context: ./client
    container_name: next-app
    command: "npm run dev"
    volumes:
      - ./client:/app
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network
  


volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
