import { PageProps } from "@/interfaces/childrenProps";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Partidos dashboard",
  description: "Generated by create next app",
};

export default function PartidosLayout({ children }: Readonly<PageProps>) {
  return <main>{children}</main>;
}
